INSERT INTO authorities(username, authority) VALUES ('admin','admin');
INSERT INTO authorities(username, authority) VALUES ('artist','artist');

--authorities artists----------------------------------------------------------------------------
INSERT INTO authorities (username, authority) VALUES ('JarrodHuffman', 'artist');
INSERT INTO authorities (username, authority) VALUES ('RossSimpson', 'artist');
INSERT INTO authorities (username, authority) VALUES ('GrayChurch', 'artist');
INSERT INTO authorities (username, authority) VALUES ('RonanMoss', 'artist');
INSERT INTO authorities (username, authority) VALUES ('DeniseMills', 'artist');
INSERT INTO authorities (username, authority) VALUES ('JoyVillarreal', 'artist');
INSERT INTO authorities (username, authority) VALUES ('AshelyGuzman', 'artist');
INSERT INTO authorities (username, authority) VALUES ('TatyanaAvila', 'artist');
INSERT INTO authorities (username, authority) VALUES ('GlennaWheeler', 'artist');
INSERT INTO authorities (username, authority) VALUES ('WinterCastro', 'artist');
INSERT INTO authorities (username, authority) VALUES ('AquilaRodriquez', 'artist');
INSERT INTO authorities (username, authority) VALUES ('OraBoyle', 'artist');
INSERT INTO authorities (username, authority) VALUES ('HedyTate', 'artist');
INSERT INTO authorities (username, authority) VALUES ('WyattHogan', 'artist');
INSERT INTO authorities (username, authority) VALUES ('RudyardRogers', 'artist');
INSERT INTO authorities (username, authority) VALUES ('HunterMcfarland', 'artist');
INSERT INTO authorities (username, authority) VALUES ('AmberWiley', 'artist');
INSERT INTO authorities (username, authority) VALUES ('MicahBurch', 'artist');
INSERT INTO authorities (username, authority) VALUES ('JaredAvery', 'artist');

--authorities producers----------------------------------------------------------------------------
INSERT INTO authorities (username, authority) VALUES ('FrancisHolder','producer');
INSERT INTO authorities (username, authority) VALUES ('EmiLogan','producer');
INSERT INTO authorities (username, authority) VALUES ('LeeRobertson','producer');
INSERT INTO authorities (username, authority) VALUES ('FlorenceCooper','producer');
INSERT INTO authorities (username, authority) VALUES ('HayesBenton','producer');
INSERT INTO authorities (username, authority) VALUES ('MarciaCollier','producer');
INSERT INTO authorities (username, authority) VALUES ('VannaHarding','producer');
INSERT INTO authorities (username, authority) VALUES ('XylaLamb','producer');
INSERT INTO authorities (username, authority) VALUES ('VeronicaDuran','producer');
INSERT INTO authorities (username, authority) VALUES ('LawrenceHolland','producer');
INSERT INTO authorities (username, authority) VALUES ('RhonaKing','producer');
INSERT INTO authorities (username, authority) VALUES ('XenaDalton','producer');
INSERT INTO authorities (username, authority) VALUES ('BarclayGoodman','producer');
INSERT INTO authorities (username, authority) VALUES ('UrsulaHenderson','producer');
INSERT INTO authorities (username, authority) VALUES ('ReeseRoberts','producer');
INSERT INTO authorities (username, authority) VALUES ('DerekRiddle','producer');
INSERT INTO authorities (username, authority) VALUES ('CameronOlson','producer');
INSERT INTO authorities (username, authority) VALUES ('AlexanderLamb','producer');
INSERT INTO authorities (username, authority) VALUES ('ZacharyLeonard','producer');
INSERT INTO authorities (username, authority) VALUES ('JerryMiranda','producer');
INSERT INTO authorities (username, authority) VALUES ('QuamarEllison','producer');
INSERT INTO authorities (username, authority) VALUES ('KirestinSantiago','producer');
INSERT INTO authorities (username, authority) VALUES ('BrettGuy','producer');
INSERT INTO authorities (username, authority) VALUES ('VenusMiles','producer');
INSERT INTO authorities (username, authority) VALUES ('DeannaWashington','producer');
INSERT INTO authorities (username, authority) VALUES ('MatthewSlater','producer');
INSERT INTO authorities (username, authority) VALUES ('ColtonDuffy','producer');
INSERT INTO authorities (username, authority) VALUES ('NissimBoyer','producer');
INSERT INTO authorities (username, authority) VALUES ('IllanaAvila','producer');
INSERT INTO authorities (username, authority) VALUES ('BuffyLynn','producer');
INSERT INTO authorities (username, authority) VALUES ('IdonaMerrill','producer');
INSERT INTO authorities (username, authority) VALUES ('MercedesDunn','producer');
INSERT INTO authorities (username, authority) VALUES ('ErichOwen','producer');
INSERT INTO authorities (username, authority) VALUES ('LillithFrench','producer');
INSERT INTO authorities (username, authority) VALUES ('DanteCoffey','producer');
INSERT INTO authorities (username, authority) VALUES ('JermaineHahn','producer');
INSERT INTO authorities (username, authority) VALUES ('LinusDennis','producer');
INSERT INTO authorities (username, authority) VALUES ('IfeomaMiles','producer');
INSERT INTO authorities (username, authority) VALUES ('EleanorCrane','producer');
INSERT INTO authorities (username, authority) VALUES ('DesiraeBuchanan','producer');
INSERT INTO authorities (username, authority) VALUES ('RudyardDiaz','producer');

--authorities writers----------------------------------------------------------------------------
INSERT INTO authorities (username, authority) VALUES ('GradyManning','writer');
INSERT INTO authorities (username, authority) VALUES ('KyleConway','writer');
INSERT INTO authorities (username, authority) VALUES ('MelyssaMedina','writer');
INSERT INTO authorities (username, authority) VALUES ('IvoryGibbs','writer');
INSERT INTO authorities (username, authority) VALUES ('GradyVincent','writer');
INSERT INTO authorities (username, authority) VALUES ('BrodyDavidson','writer');
INSERT INTO authorities (username, authority) VALUES ('WyomingSilva','writer');
INSERT INTO authorities (username, authority) VALUES ('JoanGaines','writer');
INSERT INTO authorities (username, authority) VALUES ('NatalieRowland','writer');
INSERT INTO authorities (username, authority) VALUES ('KellyLeon','writer');
INSERT INTO authorities (username, authority) VALUES ('IlianaEllis','writer');
INSERT INTO authorities (username, authority) VALUES ('OlgaLindsey','writer');
INSERT INTO authorities (username, authority) VALUES ('ElvisCastillo','writer');
INSERT INTO authorities (username, authority) VALUES ('VeraAtkinson','writer');
INSERT INTO authorities (username, authority) VALUES ('RanaRush','writer');
INSERT INTO authorities (username, authority) VALUES ('AlanaBartlett','writer');
INSERT INTO authorities (username, authority) VALUES ('NaomiMcgowan','writer');
INSERT INTO authorities (username, authority) VALUES ('HeidiMathews','writer');
INSERT INTO authorities (username, authority) VALUES ('LewisRandolph','writer');
INSERT INTO authorities (username, authority) VALUES ('StewartMarquez','writer');
INSERT INTO authorities (username, authority) VALUES ('MiriamKeller','writer');
INSERT INTO authorities (username, authority) VALUES ('FrancesSalazar','writer');
INSERT INTO authorities (username, authority) VALUES ('MosesBarrera','writer');
INSERT INTO authorities (username, authority) VALUES ('PerryBarton','writer');
INSERT INTO authorities (username, authority) VALUES ('GuinevereHorn','writer');
INSERT INTO authorities (username, authority) VALUES ('JonasJensen','writer');
INSERT INTO authorities (username, authority) VALUES ('JacksonBeck','writer');
INSERT INTO authorities (username, authority) VALUES ('QuinCollier','writer');
INSERT INTO authorities (username, authority) VALUES ('ShannonBuckner','writer');
INSERT INTO authorities (username, authority) VALUES ('AlfredaPhillips','writer');
INSERT INTO authorities (username, authority) VALUES ('IlianaDillard','writer');
INSERT INTO authorities (username, authority) VALUES ('BrynnePatton','writer');
INSERT INTO authorities (username, authority) VALUES ('JenniferBaird','writer');
INSERT INTO authorities (username, authority) VALUES ('DariaSheppard','writer');
INSERT INTO authorities (username, authority) VALUES ('ScarletHamilton','writer');
INSERT INTO authorities (username, authority) VALUES ('KaneBurch','writer');
INSERT INTO authorities (username, authority) VALUES ('SybillWilliamson','writer');
INSERT INTO authorities (username, authority) VALUES ('HedwigCarey','writer');
INSERT INTO authorities (username, authority) VALUES ('JosephineWoodard','writer');
INSERT INTO authorities (username, authority) VALUES ('AlecHill','writer');