INSERT INTO stories (title, body, genre, storylength) VALUES ('The Fault in Our Stars','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','ACCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Gone Girl','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','ACCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('City of Lost Souls','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','ACCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Pandemonium','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','ACCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Cinder','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','CIENCIA_FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Easy','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','CIENCIA_FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('The Golden Lily','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','CIENCIA_FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Slammed','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','CIENCIA_FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('The Selection','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','TERROR',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Wonder','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','TERROR',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Bared to You','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','TERROR',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Third Grave Dead Ahead','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','TERROR',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Lover Reborn','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','PSICOLOGICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Under the Never Sky','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','PSICOLOGICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Point of Retreat','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','PSICOLOGICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Defending Jacob','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','PSICOLOGICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Fourth Grave Beneath My Feet','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','HUMORISTICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Shadow of Night','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','HUMORISTICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Hallowed','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','HUMORISTICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('The Serpents Shadow','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','HUMORISTICO',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Rapture','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('The Immortal Rules','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('On Dublin Street','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Bitterblue','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','FICCION',1000);
INSERT INTO stories (title, body, genre, storylength) VALUES ('Spell Bound','En esta historia el protagonista decide abandonar su hogar y explorar el mundo','FICCION',1000);